### PR TITLE
added questions.md

### PR DESCRIPTION
**Pull request by ExploreLearnMake**
Added the Questions.md file with some content in to for the module 3.1 assignment for the campus advisors course work.

### CODE REVIEW

**Comment by ExploreLearnMake** [comment]
@mozzadrella @ericdrosado Here is my pull request.

**Comment by ericdrosado** [comment]
👋 Hi @ExploreLearnMake ! This looks great. I really like your proposed workflow. I would definitely recommend providing feedback through the Pull Request (PR) using inline comments.
Screen Shot 2019-05-10 at 8 30 27 AM
You can go to `Files changed` and you can add comments on any line of work. From there, you could also use Issues to ensure that students tend to the code that you have provided feedback/comments on. One nice thing is that you can link comments from a PR to an issue, so students know exactly what the Issue is referring to. I would also recommend waiting until the issues have been completed before approving the PR.

If you could, would you mind adding me as a reviewer to this PR? You can find information on this here:

https://help.github.com/en/articles/requesting-a-pull-request-review

This functionality is great for students to ask for review from a teacher or another student.

If you happen to have any additional questions, please feel free to reach out.

**Comment by ExploreLearnMake** [comment]
Hi @ericdrosado,
Thanks for the comments. I am unable to add you as a Reviewer. When I type in your name (with and without the @ symbol) it does nothing. I do not see you come up in a list to select, nor does hitting the Enter key do anything. It just keeps saying "Nothing to show". Did I not set something up correctly that it is blocking me from doing this?

image

EDIT: Nevermind, I realized I need to make you collaborator, so I sent that request. So once you accept I believe I'll be able to add you to the reviewer.

**Comment by ericdrosado** [comment]
Hey @ExploreLearnMake ! It looks like you figured out how to add me as a Reviewer! 🎉 🎊 

Nice work! The trick will always be to [invite collaborators](https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository) first to your repository and then you can add them as reviewers similar to how you did in `module-3-group-work-testing-team`.

This looks good to merge! Let me know if you have any additional questions.

**Pull request merged**
